# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "activeldap"
  s.version = "3.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Will Drewry", "Kouhei Sutou"]
  s.date = "2011-11-21"
  s.description = "    'ActiveLdap' is a ruby library which provides a clean\n    objected oriented interface to the Ruby/LDAP library.  It was inspired\n    by ActiveRecord. This is not nearly as clean or as flexible as\n    ActiveRecord, but it is still trivial to define new objects and manipulate\n    them with minimal difficulty.\n"
  s.email = ["redpig@dataspill.org", "kou@cozmixng.org"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.textile",
    "TODO"
  ]
  s.files = [
    "COPYING",
    "Gemfile",
    "LICENSE",
    "README.textile",
    "TODO",
    "benchmark/bench-al.rb",
    "benchmark/config.yaml.sample",
    "doc/text/development.textile",
    "doc/text/news.textile",
    "doc/text/rails.textile",
    "doc/text/tutorial.textile",
    "examples/config.yaml.example",
    "examples/example.der",
    "examples/example.jpg",
    "examples/groupadd",
    "examples/groupdel",
    "examples/groupls",
    "examples/groupmod",
    "examples/lpasswd",
    "examples/objects/group.rb",
    "examples/objects/ou.rb",
    "examples/objects/user.rb",
    "examples/ouadd",
    "examples/useradd",
    "examples/useradd-binary",
    "examples/userdel",
    "examples/userls",
    "examples/usermod",
    "examples/usermod-binary-add",
    "examples/usermod-binary-add-time",
    "examples/usermod-binary-del",
    "examples/usermod-lang-add",
    "lib/active_ldap.rb",
    "lib/active_ldap/action_controller/ldap_benchmarking.rb",
    "lib/active_ldap/acts/tree.rb",
    "lib/active_ldap/adapter/base.rb",
    "lib/active_ldap/adapter/jndi.rb",
    "lib/active_ldap/adapter/jndi_connection.rb",
    "lib/active_ldap/adapter/ldap.rb",
    "lib/active_ldap/adapter/ldap_ext.rb",
    "lib/active_ldap/adapter/net_ldap.rb",
    "lib/active_ldap/adapter/net_ldap_ext.rb",
    "lib/active_ldap/association/belongs_to.rb",
    "lib/active_ldap/association/belongs_to_many.rb",
    "lib/active_ldap/association/children.rb",
    "lib/active_ldap/association/collection.rb",
    "lib/active_ldap/association/has_many.rb",
    "lib/active_ldap/association/has_many_utils.rb",
    "lib/active_ldap/association/has_many_wrap.rb",
    "lib/active_ldap/association/proxy.rb",
    "lib/active_ldap/associations.rb",
    "lib/active_ldap/attributes.rb",
    "lib/active_ldap/base.rb",
    "lib/active_ldap/callbacks.rb",
    "lib/active_ldap/command.rb",
    "lib/active_ldap/compatible.rb",
    "lib/active_ldap/configuration.rb",
    "lib/active_ldap/connection.rb",
    "lib/active_ldap/distinguished_name.rb",
    "lib/active_ldap/entry_attribute.rb",
    "lib/active_ldap/escape.rb",
    "lib/active_ldap/get_text.rb",
    "lib/active_ldap/get_text/parser.rb",
    "lib/active_ldap/get_text_fallback.rb",
    "lib/active_ldap/get_text_support.rb",
    "lib/active_ldap/helper.rb",
    "lib/active_ldap/human_readable.rb",
    "lib/active_ldap/ldap_error.rb",
    "lib/active_ldap/ldif.rb",
    "lib/active_ldap/log_subscriber.rb",
    "lib/active_ldap/object_class.rb",
    "lib/active_ldap/operations.rb",
    "lib/active_ldap/persistence.rb",
    "lib/active_ldap/populate.rb",
    "lib/active_ldap/railtie.rb",
    "lib/active_ldap/railties/controller_runtime.rb",
    "lib/active_ldap/schema.rb",
    "lib/active_ldap/schema/syntaxes.rb",
    "lib/active_ldap/timeout.rb",
    "lib/active_ldap/timeout_stub.rb",
    "lib/active_ldap/user_password.rb",
    "lib/active_ldap/validations.rb",
    "lib/active_ldap/xml.rb",
    "lib/rails/generators/active_ldap/model/USAGE",
    "lib/rails/generators/active_ldap/model/model_generator.rb",
    "lib/rails/generators/active_ldap/model/templates/model_active_ldap.rb",
    "lib/rails/generators/active_ldap/scaffold/scaffold_generator.rb",
    "lib/rails/generators/active_ldap/scaffold/templates/ldap.yml",
    "po/en/active-ldap.po",
    "po/ja/active-ldap.po"
  ]
  s.homepage = "http://ruby-activeldap.rubyforge.org/"
  s.licenses = ["Ruby's or GPLv2 or later"]
  s.require_paths = ["lib"]
  s.rubyforge_project = "ruby-activeldap"
  s.rubygems_version = "1.8.10"
  s.summary = "ActiveLdap is a object-oriented API to LDAP"
  s.test_files = ["test/test_adapter.rb", "test/test_connection.rb", "test/test_schema.rb", "test/test_base_per_instance.rb", "test/test_configuration.rb", "test/test_groupdel.rb", "test/test_user_password.rb", "test/test_callback.rb", "test/test_object_class.rb", "test/test_userls.rb", "test/test_dn.rb", "test/test_ldif.rb", "test/test_acts_as_tree.rb", "test/test_base.rb", "test/test_find.rb", "test/test_lpasswd.rb", "test/test_bind.rb", "test/test_connection_per_dn.rb", "test/test_usermod-binary-del.rb", "test/test_load.rb", "test/test_userdel.rb", "test/test_groupmod.rb", "test/test_useradd.rb", "test/test_attributes.rb", "test/test_reflection.rb", "test/test_user.rb", "test/test_usermod-lang-add.rb", "test/test_groupls.rb", "test/test_usermod.rb", "test/test_groupadd.rb", "test/test_useradd-binary.rb", "test/test_usermod-binary-add-time.rb", "test/test_validation.rb", "test/test_usermod-binary-add.rb", "test/test_syntax.rb", "test/test_associations.rb", "test/test_connection_per_class.rb"]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activemodel>, ["~> 3.1.0"])
      s.add_runtime_dependency(%q<locale>, [">= 0"])
      s.add_runtime_dependency(%q<fast_gettext>, [">= 0"])
      s.add_runtime_dependency(%q<gettext_i18n_rails>, [">= 0"])
      s.add_development_dependency(%q<ruby-ldap>, [">= 0"])
      s.add_development_dependency(%q<net-ldap>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<test-unit>, [">= 0"])
      s.add_development_dependency(%q<test-unit-notify>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_development_dependency(%q<RedCloth>, [">= 0"])
    else
      s.add_dependency(%q<activemodel>, ["~> 3.1.0"])
      s.add_dependency(%q<locale>, [">= 0"])
      s.add_dependency(%q<fast_gettext>, [">= 0"])
      s.add_dependency(%q<gettext_i18n_rails>, [">= 0"])
      s.add_dependency(%q<ruby-ldap>, [">= 0"])
      s.add_dependency(%q<net-ldap>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<test-unit>, [">= 0"])
      s.add_dependency(%q<test-unit-notify>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<RedCloth>, [">= 0"])
    end
  else
    s.add_dependency(%q<activemodel>, ["~> 3.1.0"])
    s.add_dependency(%q<locale>, [">= 0"])
    s.add_dependency(%q<fast_gettext>, [">= 0"])
    s.add_dependency(%q<gettext_i18n_rails>, [">= 0"])
    s.add_dependency(%q<ruby-ldap>, [">= 0"])
    s.add_dependency(%q<net-ldap>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<test-unit>, [">= 0"])
    s.add_dependency(%q<test-unit-notify>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<RedCloth>, [">= 0"])
  end
end

